test: multi-path

diff --git a/.github/workflows/ci-test-ulcl.yml b/.github/workflows/ci-test-ulcl.yml
--- a/.github/workflows/ci-test-ulcl.yml
+++ b/.github/workflows/ci-test-ulcl.yml
@@ -35,7 +35,7 @@ jobs:
             echo "Failed to up docker compose TI"
             exit 1
           fi
-          sleep 5 # wait for docker compose to finish
+          sleep 5
 
       - name: Run ULCL TI test
         run: |
@@ -48,6 +48,29 @@ jobs:
         run: |
           if ! docker compose -f ${{ env.TI_COMPOSE_FILE }} down; then
             echo "Failed to down docker compose TI"
+            exit 1
+          fi
+
+      - name: Up MP docker compose
+        run: |
+          if ! docker compose -f ${{ env.MP_COMPOSE_FILE }} up -d --wait --wait-timeout ${{ env.WAIT_TIMEOUT }}; then
+            echo "Failed to up docker compose MP"
+            exit 1
+          fi
+          sleep 5
+
+      - name: Run ULCL MP test
+        run: |
+          set -e
+          echo "Starting ULCL MP test..."
+          docker exec ci-1 /bin/bash -c "cd /root/test && ./test-ulcl-mp.sh TestULCLMultiPathCi1"
+          docker exec ci-2 /bin/bash -c "cd /root/test && ./test-ulcl-mp.sh TestULCLMultiPathCi2"
+
+      - name: Down MP docker compose
+        if: always()
+        run: |
+          if ! docker compose -f ${{ env.MP_COMPOSE_FILE }} down; then
+            echo "Failed to down docker compose MP"
             exit 1
           fi
 
